### ISSUE TITLE
We need a website

### ISSUE THREAD

**Issue by essial** [essial/OpenDiablo2#25]
If you're good at doing websites, this is a perfect way to contribute! We need a website set up for this project. There will be downloads available soon so make a space for that as well. I don't really care what it looks like, as long as it doesn't look too terrible.

**Comment by Kamori** [comment]
What sort of data are you hoping to have on the site?

Here is what I can think of so far.

1. Link back to github
2. Duplicate some of the About/contributing stuff from Readme

Are you hoping to use the docs as internal api documentation as well?

**Comment by essial** [comment]
Just a general info site. Current state, how to build and/or run in various environments, etc.

And yes, eventually I'd like to start adding the specifications, formats, etc that we discover once we get the game more complete. There's info 'out there', but its extremely old, and disappearing fast. I'm not in a rush to get the site done, just keeping this item out there in case someone wants to tackle it.
