### ISSUE TITLE
Website has invalid SSL cert.

### ISSUE THREAD

**Issue by ilar** [essial/OpenDiablo2#33]
**Describe the bug**
The SSL cert for opendiablo2.com is invalid.

**To Reproduce**
1. Go to https://www.opendiablo2.com
2. Privacy error.

**Expected behavior**
The website should show, not the SSL browser warning.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac/Android
 - Version: Mojave/8.1

**Additional context**
N/A

**Comment by essial** [comment]
You are absolutely correct, I'll fix this tonight, though do note there is no website to visit yet either way.

**Comment by essial** [comment]
Are you saying it's still broken? Seems to be ok now. I'll close if so.

**Comment by essial** [comment]
Looks like I'll eventually have to just spin up a container and host it there. For now we'll just table the website. I'll close the tickets.
