### ISSUE TITLE
Map cache needs to expire

### ISSUE THREAD

**Issue by essial** [essial/OpenDiablo2#46]
The cell data for maps need to expire after some time after not being accessed. Now that we are generating more and more map data, we will have a lot of areas locked into memory that we are nowhere near. This works into the GetMapCellInfo logic somehow.

**Comment by Kamori** [comment]
Does this mean the desired goal is, if someone leaves act 1 to venture into act 2, if they come back to act 1 X time later, start regenerating the maps?

Or what is the expect behavior?

**Comment by essial** [comment]
Right now we don't really support multiple acts. That'l be added in a bit later.

So MapInfo and SubMapInfo have a dictionary of map cells. GetMapCellInfo in GameState will either returned the cached copy, or generate the new data as needed. Obviously this will stay in memory forever as there is no mechanism to expire this information.

The memory usage isn't TOO bad, but it still seems wasteful to keep cell info around when you're 10 minutes away from the area.

To put it more clearly, imagine an effectively infinite plain of grid spaces. When the map wants to render a cell, it first finds a map that occupies that cell (technically, the LAST map in case of overlap), and looks up that specific map's cell data (or pulls it from cache). That way, we don't have to generate all of the art for all of the map all at once.
