### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by cardoso** [essial/OpenDiablo2#60]
Hi! Thanks for starting this amazing project.

Here's my assessment on trying to run it on macOS:

1. System.Collections.Immutable is not recognized during compilation, so I replaced all references with the System.Collections.Generic equivalents and it compiles, so I can now run it.

2. After that, it shows a blank screen and crashes with "Decryption failed" for D2xMusic.mpq, so I disabled all code related to music, so now it shows the main screen (although with some graphical glitches).

3. After that, I try starting singleplayer, it shows the loading screen (non-animated), but it crashes with "Decryption failed" for d2exp.mpq. (I can: look into the credits, after seeing a non-animated loading screen, open GitHub page, exit game)

Any help I can get with fixing "Decryption failed"? I doubt I can figure this out on my own. With other bugs or missing features, I might be able to help :)

# Extra info

Here are some screens of it running on macOS: https://imgur.com/a/xz8bonF

I'm using Visual Studio for macOS with Mono. 

I tried running with:
- Diablo 2 macOS 1.14d LOD, 
- Diablo 2 Windows 1.14d LOD, 
- Diablo 2 Windows 1.13c LOD

All to similar results.

**Comment by essial** [comment]
I'd recommend joining the discord channel and working with us on there. I'll be on later this afternoon. I do know that aftet adding patch support it broke non windows builds, even on my machine. I guess we need to prioritize that. Also I may revert the immutable collections as that does seem to also cause build issues in certain environments. Also make sure you have both the base and expansion installed, and update it to the latest version.

**Comment by cardoso** [comment]
@essial yes, I'm using LOD for all the tests. I can submit the immutable collections removal if that's Ok
